# ── PostgreSQL Datasource ──
spring.datasource.url=jdbc:postgresql://localhost:5432/lab8shop
spring.datasource.username=postgres
spring.datasource.password=kanditat3113

# ── JPA / Hibernate ──
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── Thymeleaf (ปิด cache ระหว่างพัฒนา) ──
spring.thymeleaf.cache=false

# ── Server ──
server.port=8080
